libsysmap="../../lib/libsys/syscalls.map"
libsys_h="../../lib/libsys/_libsys.h"
sysmk="../sys/syscall.mk"
syshdr_extra="#define 	SYS_exit	SYS__exit"

# Retire old native dispatch while preserving published constants and exports.
mincompat="11"
sysproto_shared="#ifdef COMPAT_FREEBSD32\n#include <compat/freebsd32/freebsd32_legacy_proto.h>\n#endif"
