#!/bin/sh
#
# PROVIDE: ipfw
# REQUIRE: netif
# BEFORE: NETWORKING
# KEYWORD: nojailvnet

. /etc/rc.subr
. /etc/network.subr

name="ipfw"
desc="Mandatory HalfBSD firewall policy"
start_cmd="ipfw_start"
reload_cmd="ipfw_start"
restart_cmd="ipfw_start"
stop_cmd="ipfw_stop"
status_cmd="ipfw_status"
extra_commands="reload status"

ipfw_start()
{
	/bin/sh /etc/rc.firewall "${1:-${firewall_mode:-open}}"
}

ipfw_stop()
{
	warn "IPFW is always enabled; select firewall_mode=open to permit traffic"
	return 1
}

ipfw_status()
{
	local status

	status=$(${SYSCTL} -n net.inet.ip.fw.enable) || return 1
	[ "${status}" = 1 ] || return 1
	if afexists inet6; then
		status=$(${SYSCTL} -n net.inet6.ip6.fw.enable) || return 1
		[ "${status}" = 1 ] || return 1
	fi
	echo "IPFW is enabled; configured mode: ${firewall_mode:-open}"
}

load_rc_config $name

# Policy management runs on the host, not in a service jail.
ipfw_svcj="NO"

run_rc_command "$@"
