#!/bin/sh
#
#

# PROVIDE: mountcritremote
# REQUIRE: NETWORKING FILESYSTEMS ipsec netwait
# KEYWORD: nojail

. /etc/rc.subr

name="mountcritremote"
desc="Mount critical remote filesystems"
stop_cmd=":"
start_cmd="mountcritremote_start"

mountcritremote_start()
{
	local mounted_remote_filesystem=false

	# Mount network filesystems if present in /etc/fstab.
	case ${extra_netfs_types} in
	[Nn][Oo])
		;;
	*)
		netfs_types="${netfs_types} ${extra_netfs_types}"
		;;
	esac

	for i in ${netfs_types}; do
		fstype=${i%:*}
		fsdecr=${i#*:}

		case "`mount -d -a -t ${fstype}`" in
		*mount_${fstype}*)
			mounted_remote_filesystem=true
			echo -n "Mounting ${fsdecr} filesystems:"
			mount -a -t ${fstype}
			echo '.'
			;;
		esac
	done

	if $mounted_remote_filesystem; then
		# Cleanup /var again just in case it's a network mount.
		/etc/rc.d/cleanvar quietreload
		rm -f /var/run/clean_var /var/spool/lock/clean_var

		# Regenerate the ldconfig hints in case there are additional
		# library paths on remote file systems
		/etc/rc.d/ldconfig quietstart
	fi
}

load_rc_config $name

# mounting shall not be performed in a svcj
mountcritremote_svcj="NO"

run_rc_command "$1"
